#+TITLE: Introduction to HotDrink
#+LANGUAGE:  en
#+OPTIONS: H:2 author:nil creator:nil
#+HTML_HEAD_EXTRA: <script type="text/javascript" src="hotdrink.min.js"></script>
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="style.css"/>
# #+INFOJS_OPT: sdepth:1 home:index.html

* Overview of basic concepts

HotDrink is a JavaScript library that assists with GUI implementation.
HotDrink allows you to program GUIs /declaratively/---instead of
writing event handlers that control what should happen in a GUI and when,
the programmer specifies the relationships between various pieces of
data in the GUI and ways in which those relationships may be enforced.
From this description, HotDrink decides how and when to enforce relationships,
and also implements several GUI behaviors
that can be reused with little effort.

** Constraint systems

The heart of the HotDrink library is a /constraint system/.  A
constraint system manages variables and /constraints/ among the variables.  Each
constraint represents something that should be true concerning some of the
variables (i.e., a /relation/ over those variables).
For example, given three variables, $x$, $y$, and $z$, you
could create a constraint that $x = y + z$, or that $x \le y \le z$, or even that $z$
is the result of a database query using $x$ and $y$.  When the
constraint is true, we say it is /satisfied/.  HotDrink /enforces/ a
constraint by modifying some of the variables involved so that the constraint is
satisfied.

In HotDrink's constraint system, constraints between variables are expressed
as sets of functions.  These functions are called /methods/ (short for
/constraint satisfaction methods/) and are written by the programmer.  Each
method is responsible for calculating new values for some of the constraint's
variables so that the constraint will be satisfied.  To enforce all
constraints, HotDrink executes one method from each constraint.  Together, the
methods executed define a /dataflow/ --- a branching path showing which
variables are used to update which other variables.  HotDrink has a
/multi-way dataflow constraint system/, meaning there are many possible
dataflows depending on which methods are executed.  In general, HotDrink
selects a dataflow that preserves variables the user has edited more recently.

In a HotDrink \ldquo{}powered\rdquo{} user interface, GUI events are translated to changes
to constraint system variables.  These changes result
in constraints which are no longer satisfied.  HotDrink
responds by /solving/ the constraint system --- that is, selecting which methods
to execute, and then executing them so that all constraints are again
satisfied.  Solving can change the values of the system's variables; the
changed values are then somehow
displayed or visualized to the user, as specified by the programmer.

** MVVM

Applications written with HotDrink follow the Model-View-ViewModel
(a.k.a. MVVM) design pattern.  This pattern divides the application as
follows:

- The /view/ is responsible for presentation and capturing
  interactions with the user.  It arranges everything on the screen
  and provides events that indicate user actions.  For our purposes,
  the view is specified in HTML, along with JavaScript that
  generates and modifies the HTML.  This tutorial shows bits and snippets of HTML, with
  some commentary to help understand the examples, but in general we assume familiarity
  with HTML, JavaScript, and constructing web pages.

- The /view-model/ is responsible for managing the data presented in
  the view. This means supplying the data to the view to be displayed,
  as well as responding to user actions.  The purpose of
  HotDrink is to help in implementing the view-model.

- Another important part of an MVVM application are the /bindings/.  A
  binding connects elements in the view with variables in the
  view-model.  The bindings are sometimes treated as part of the
  view---that is why there is no "B" in "MVVM"---but we treat them as
  a distinct component of the pattern.  In HotDrink, bindings can be
  specified in JavaScript, or as annotations in HTML as part of the
  view specification.

- The /model/ is responsible for everything else---whatever the
  application is actually supposed to /do/.  The model does not need to
  be aware of the user interface; therefore we will not discuss it further in
  this documentation.

* Including HotDrink in your web page

To use HotDrink, include the file [[file:hotdrink.min.js][=hotdrink.min.js=]] that came with
this tutorial.  Alternatively, if you downloaded the source tree,
follow the build instructions to compile your own =hotdrink.min.js=.

More specifically, that means adding the following ~<script>~ tag to
the ~<head>~ section
of your HTML, with the appropriate path in the ~src~ attribute.  In
order for the examples in this tutorial to work, the file
=hotdrink.min.js= must be located in the same directory as this HTML
file.

#+BEGIN_SRC html
<script type="text/javascript" src="hotdrink.min.js"></script>
#+END_SRC

HotDrink does not rely on any other JavaScript frameworks, but neither should it
conflict with other frameworks (JQuery, Dojo, MooTools, etc.).
The only global symbol it exports is ~hd~, and all of its interactions
with the DOM are via cooperative API functions, e.g.,
[[https://developer.mozilla.org/en-US/docs/Web/API/EventTarget.addEventListener][~addEventListener~]], etc.

* Important HotDrink objects

There are three important objects which you will need to interact with when
using HotDrink.

** The property model

A /property model/ is the view-model of your application.  It contains
variables for holding the data used by your GUI, and also a constraint system
for enforcing any constraints you define over those variables as described in
Section [[Constraint systems]].  In general, your application will always have a
single property model, created like so:

#+BEGIN_SRC js
var pm = new hd.PropertyModel();
#+END_SRC

** The context

A /context/ is an object which serves two purposes.  First, it is a container
for variables and constraints of the property model.  Second, it provides a
naming mechanism: if you want a variable named $x$, create a new variable
object and assign it to the the ~x~ field of your context.  We say the
variable is named ~x~ in the context to which you assigned it; the same
variable may have a different name in some other context.

To a context, containing an object and naming an object are two different
things.  The context may contain certain objects which it does not name, and
it may name objects which it does not contain.  Containing denotes ownership:
a context owns the variables and constraints it contains.  Thus, while
multiple contexts may give a name to a variable, only one context may contain
a variable.  When you add a context to a property model, you add all the
variables and constraints which it contains.

** The context builder

The task of building a context is rather complex.  To help, HotDrink contains
an object called the /context builder/.  This object essentially defines its
own language (i.e., an /embedded domain-specific language/) for constructing
contexts.  To use this language, create a new context builder instance, then
call its member functions to add elements to the context.  These member
functions are described in detail in [[file:basics.org][Basic HotDrink Usage]].  The ~context~
member function retrieves the constructed context.

#+BEGIN_SRC js
var builder = new hd.ContextBuilder();

// ...invoke various builder member functions to build the model ...

var context = builder.context();
#+END_SRC

Once you have a context, you may add it to the property model.

#+BEGIN_SRC js
pm.addComponent( context );
#+END_SRC

As those function names suggest, the full model for your application can
actually consist of several different components, and new components can be
added or removed at run-time.  For now we assume one component only and
consider it as the entire model.
