# Makefile for HotDrink tests.

include $(MAKEDIR)/Makefile.common
include $(MAKEDIR)/Makefile.js

##################################################
# mandatory configuration

TITLE := hotdrink-test

##################################################
# optional configuration

SRCDIR := test/qunit
SOURCES := \
	common/hottest.js \
	bindings/binders/html/attr.js \
	bindings/binders/html/text.js \
	bindings/binders/html/html.js \
	bindings/binders/html/style.js \
	bindings/binders/html/css.js \
	bindings/binders/html/visible.js \
	bindings/expressions.js \
	#common/hello_world.js \
	common/full_name.js \
  common/cycle.js \
	common/resize_image.js \
	common/save_image.js \
	common/hard_minmax.js \
	common/grouped_options.js \
	model/value.js \
	model/enablement.js

HEADERS := \
  lib/utility/debug.m4.js

