# I provide helpers for Makefiles.

##################################################
# standard library

hide   = $(dir $1).$(notdir $1)
unhide = $(dir $1)$(patsubst .%,%,$(notdir $1))

watch = echo $1 := $($1)

empty :=
space := $(empty) $(empty)

defer = $(MAKE) -f $1 $@

