#!/bin/sh

# Dependencies
# Set paths appropriately to the 'core' jslint javascript file
# and to the jslint wrapper script
#
JSLINT=fulljslint.js
JSC_WRAPPER=jsc_jslint_wrapper.js

if [ $# = "0" ]
then
	echo 'Usage:\n  jslint file(s)'
	echo '\nExamples:'
	echo '  jslint file.js file2.js'
	echo '  jslint folder/*.js folder2/*.js'

else
	#Loop over arguments, invoking jslint for each file separetely
	for sourcefile in "$@"
	do
		echo "=== $sourcefile ==="

		#Check that file exists
		if [ ! -r $sourcefile -o ! -s $sourcefile ]
		then
			echo "FIle is not readable or empty"
			continue
		fi

		# Invoke jslint via jsc
		/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Resources/jsc  $JSLINT $JSC_WRAPPER -- "`cat $sourcefile`"
		# If you have a link to jsc on your path, then you can comment out the previous line and uncomment the next one ...
		# jsc  $JSLINT $JSC_WRAPPER -- "`cat $sourcefile`"

		echo "==="
	done
fi
