#!/bin/sh

# Dependencies
# Set paths appropriately to the 'core' jslint javascript file
# and to the jslint wrapper script
#
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
JSLINT=$DIR/jslint.js
JSC_WRAPPER=$DIR/jslint_wrapper.js

if [[ $OSTYPE == darwin* ]]; then
	JS_SHELL=/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Resources/jsc
	# If you have a link to jsc on your path, then you can comment out the previous line and uncomment the next one ...
	#JS_SHELL=jsc
	FILES="$JSC_WRAPPER -- $JSLINT"
elif [[ $OSTYPE == linux-gnu ]]; then
	JS_SHELL=rhino
	FILES="$JSC_WRAPPER $JSLINT"
else
	echo "JSLint Error: OS not supported"
	exit 0
fi

if [ $# = "0" ]
then
	echo 'Usage:\n  jslint file(s)'
	echo '\nExamples:'
	echo '  jslint file.js file2.js'
	echo '  jslint folder/*.js folder2/*.js'

else
	#Loop over arguments, invoking jslint for each file separetely
	for sourcefile in "$@"
	do
		echo "=== $sourcefile ==="

		#Check that file exists
		if [ ! -r $sourcefile -o ! -s $sourcefile ]
		then
			echo "FIle is not readable or empty"
			continue
		fi

		"$JS_SHELL" $FILES "`cat $sourcefile`"

		echo "==="
	done
fi
